global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "node-exporter"
    static_configs:
      - targets: ["localhost:9100"] # localhostから変更

  - job_name: "node-exporter-nuc"
    static_configs:
      - targets: ["100.114.200.30:9100"]

  - job_name: "speedtest"
    scrape_interval: 1h
    scrape_timeout: 300s
    static_configs:
      - targets: ['localhost:9798']

  - job_name: "speedtest-nuc"
    scrape_interval: 1h
    scrape_timeout: 300s
    static_configs:
      - targets: ['100.114.200.30:9798']


